name: Pyrogram-Gokil

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Generate API
        run: |
          make venv
          make api

      - name: Run tests
        run: |
          tox

  debian-build:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip install tox

      - name: Install specific Python version
        run: |
          apt-get update
          apt-get install -y python${{ matrix.python-version }} python3-venv python3-wheel
          update-alternatives --install /usr/bin/python python /usr/bin/python${{ matrix.python-version }} 1

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip

      - name: Install project dependencies
        run: |
          pip install tox

      - name: Generate API
        run: |
          make venv
          make api

      - name: Fix permissions
        run: |
          chown -R $(whoami) /github/home/.cache/pip || true

      - name: Run tests
        run: |
          tox
          
