name: Pyrogram-Gokil

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, debian-11]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Set up system
        if: matrix.os == 'debian-11'
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Generate API
        run: |
          make venv
          make api

      - name: Run tests
        run: |
          tox

  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        
    steps:
      - name: Set up system
        uses: actions/checkout@v3

      - name: Install Python
        run: |
          apt-get update
          apt-get install -y python${{ matrix.python-version }} python3-pip
          python${{ matrix.python-version }} -m pip install --upgrade pip
          python${{ matrix.python-version }} -m pip install tox

      - name: Generate API
        run: |
          make venv
          make api

      - name: Run tests
        run: |
          tox
